# Generated by Django 4.2.9 on 2025-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=20)),
                ("Name", models.CharField(max_length=20)),
                ("Email", models.CharField(max_length=20)),
                ("Password", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=30)),
            ],
        ),
    ]
