# Generated by Django 4.2.9 on 2025-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contact", new_name="register",),
    ]
