# Generated by Django 4.2.9 on 2025-01-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0002_rename_contact_register"),
    ]

    operations = [
        migrations.RemoveField(model_name="register", name="message",),
    ]
