# Generated by Django 4.2.9 on 2025-01-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0003_remove_register_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="log_in",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="register", old_name="Email", new_name="email",
        ),
        migrations.RenameField(
            model_name="register", old_name="Name", new_name="name",
        ),
        migrations.RenameField(
            model_name="register", old_name="Password", new_name="password",
        ),
        migrations.RenameField(
            model_name="register", old_name="UserName", new_name="username",
        ),
    ]
