# Generated by Django 4.2.9 on 2025-01-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0004_log_in_rename_email_register_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log_in", old_name="userName", new_name="username",
        ),
    ]
